steps:

- powershell: |
    $nodeVersion = "$(NODE_VERSION)"
    $nodeMajorVersion = $nodeVersion.split(".")[0]
    Write-Output ("##vso[task.setvariable variable=NodeMajorVersion;]$nodeMajorVersion")
  displayName: "Get Major Version Number of NodeJS Using PowerShell"
  